$file = "src\app\pages\home\home.html"
$arr = [System.IO.File]::ReadAllLines($file, [System.Text.Encoding]::UTF8)

# New content for lines 284-382 (0-indexed: 283 to 381 inclusive)
# We keep lines 0..282, inject new block, then lines 382 onward
$newBlock = @(
"    <!-- Service Cards Grid -->",
"    <div class=""grid grid-cols-1 md:grid-cols-3 gap-6 animate-fade-in-up delay-200"">",
"",
"      <!-- Card 1: Frontend Dev -->",
"      <div class=""perspective-container card-enter card-delay-1 animate-float""",
"           (mousemove)=""onServiceMouseMove(`$event, 0)""",
"           (mouseleave)=""resetServiceCardTilt(0)"">",
"        <div class=""relative group rounded-2xl overflow-hidden bg-white border border-slate-200 shadow-lg hover:shadow-cyan-200/40 hover:shadow-xl transition-all duration-500 cursor-default will-change-transform""",
"             [style.transform]=""serviceCardTransforms()[0]"">",
"          <div class=""pointer-events-none absolute inset-0 transition duration-500 opacity-0 group-hover:opacity-100 z-10""",
"               [style.background]=""'radial-gradient(400px circle at ' + serviceSpotlights()[0].x + 'px ' + serviceSpotlights()[0].y + 'px, rgba(6,182,212,0.08), transparent 60%)'""></div>",
"          <div class=""absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-cyan-400 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 z-20""></div>",
"          <div class=""absolute top-6 right-7 text-6xl font-black text-slate-100 group-hover:text-cyan-50 select-none transition-colors duration-500 leading-none"">01</div>",
"          <div class=""relative z-10 p-8 pt-10"">",
"            <div class=""w-14 h-14 rounded-2xl bg-cyan-50 border border-cyan-100 flex items-center justify-center text-cyan-500 mb-6 group-hover:bg-cyan-500 group-hover:text-white group-hover:border-cyan-500 group-hover:shadow-[0_0_24px_rgba(6,182,212,0.35)] transition-all duration-500 bounce-icon"">",
"              <svg xmlns=""http://www.w3.org/2000/svg"" class=""h-7 w-7"" fill=""none"" viewBox=""0 0 24 24"" stroke=""currentColor"">",
"                <path stroke-linecap=""round"" stroke-linejoin=""round"" stroke-width=""2"" d=""M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"" />",
"              </svg>",
"            </div>",
"            <h3 class=""text-xl font-black text-slate-900 mb-3 group-hover:text-cyan-600 transition-colors duration-300"">Frontend Dev</h3>",
"            <p class=""text-slate-500 text-sm leading-relaxed"">Building responsive, single-page applications using Angular and React. Clean, semantic, and SEO-friendly code.</p>",
"            <div class=""mt-6 pt-5 border-t border-slate-100"">",
"              <span class=""text-xs font-bold uppercase tracking-widest text-slate-400 group-hover:text-cyan-500 transition-colors duration-300"">Angular · React · TypeScript</span>",
"            </div>",
"          </div>",
"        </div>",
"      </div>",
"",
"      <!-- Card 2: UI/UX Design -->",
"      <div class=""perspective-container card-enter card-delay-2 animate-float-slow""",
"           (mousemove)=""onServiceMouseMove(`$event, 1)""",
"           (mouseleave)=""resetServiceCardTilt(1)"">",
"        <div class=""relative group rounded-2xl overflow-hidden bg-white border border-slate-200 shadow-lg hover:shadow-purple-200/40 hover:shadow-xl transition-all duration-500 cursor-default will-change-transform""",
"             [style.transform]=""serviceCardTransforms()[1]"">",
"          <div class=""pointer-events-none absolute inset-0 transition duration-500 opacity-0 group-hover:opacity-100 z-10""",
"               [style.background]=""'radial-gradient(400px circle at ' + serviceSpotlights()[1].x + 'px ' + serviceSpotlights()[1].y + 'px, rgba(168,85,247,0.08), transparent 60%)'""></div>",
"          <div class=""absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-purple-400 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 z-20""></div>",
"          <div class=""absolute top-6 right-7 text-6xl font-black text-slate-100 group-hover:text-purple-50 select-none transition-colors duration-500 leading-none"">02</div>",
"          <div class=""relative z-10 p-8 pt-10"">",
"            <div class=""w-14 h-14 rounded-2xl bg-purple-50 border border-purple-100 flex items-center justify-center text-purple-500 mb-6 group-hover:bg-purple-500 group-hover:text-white group-hover:border-purple-500 group-hover:shadow-[0_0_24px_rgba(168,85,247,0.35)] transition-all duration-500 bounce-icon"">",
"              <svg xmlns=""http://www.w3.org/2000/svg"" class=""h-7 w-7"" fill=""none"" viewBox=""0 0 24 24"" stroke=""currentColor"">",
"                <path stroke-linecap=""round"" stroke-linejoin=""round"" stroke-width=""2"" d=""M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01"" />",
"              </svg>",
"            </div>",
"            <h3 class=""text-xl font-black text-slate-900 mb-3 group-hover:text-purple-600 transition-colors duration-300"">UI/UX Design</h3>",
"            <p class=""text-slate-500 text-sm leading-relaxed"">Designing intuitive interfaces with Figma. Focusing on typography, spacing, and color theory for engaging user journeys.</p>",
"            <div class=""mt-6 pt-5 border-t border-slate-100"">",
"              <span class=""text-xs font-bold uppercase tracking-widest text-slate-400 group-hover:text-purple-500 transition-colors duration-300"">Figma · Wireframing · Prototyping</span>",
"            </div>",
"          </div>",
"        </div>",
"      </div>",
"",
"      <!-- Card 3: Optimization -->",
"      <div class=""perspective-container card-enter card-delay-3 animate-float-delayed""",
"           (mousemove)=""onServiceMouseMove(`$event, 2)""",
"           (mouseleave)=""resetServiceCardTilt(2)"">",
"        <div class=""relative group rounded-2xl overflow-hidden bg-white border border-slate-200 shadow-lg hover:shadow-blue-200/40 hover:shadow-xl transition-all duration-500 cursor-default will-change-transform""",
"             [style.transform]=""serviceCardTransforms()[2]"">",
"          <div class=""pointer-events-none absolute inset-0 transition duration-500 opacity-0 group-hover:opacity-100 z-10""",
"               [style.background]=""'radial-gradient(400px circle at ' + serviceSpotlights()[2].x + 'px ' + serviceSpotlights()[2].y + 'px, rgba(59,130,246,0.08), transparent 60%)'""></div>",
"          <div class=""absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-blue-400 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 z-20""></div>",
"          <div class=""absolute top-6 right-7 text-6xl font-black text-slate-100 group-hover:text-blue-50 select-none transition-colors duration-500 leading-none"">03</div>",
"          <div class=""relative z-10 p-8 pt-10"">",
"            <div class=""w-14 h-14 rounded-2xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-500 mb-6 group-hover:bg-blue-500 group-hover:text-white group-hover:border-blue-500 group-hover:shadow-[0_0_24px_rgba(59,130,246,0.35)] transition-all duration-500 bounce-icon"">",
"              <svg xmlns=""http://www.w3.org/2000/svg"" class=""h-7 w-7"" fill=""none"" viewBox=""0 0 24 24"" stroke=""currentColor"">",
"                <path stroke-linecap=""round"" stroke-linejoin=""round"" stroke-width=""2"" d=""M13 10V3L4 14h7v7l9-11h-7z"" />",
"              </svg>",
"            </div>",
"            <h3 class=""text-xl font-black text-slate-900 mb-3 group-hover:text-blue-600 transition-colors duration-300"">Optimization</h3>",
"            <p class=""text-slate-500 text-sm leading-relaxed"">Optimizing for speed and efficiency. Lazy loading, efficient state management, and smooth performance.</p>",
"            <div class=""mt-6 pt-5 border-t border-slate-100"">",
"              <span class=""text-xs font-bold uppercase tracking-widest text-slate-400 group-hover:text-blue-500 transition-colors duration-300"">Performance · SEO · Core Web Vitals</span>",
"            </div>",
"          </div>",
"        </div>",
"      </div>",
"",
"    </div>"
)

# lines 0..282 = before (lines 1-283), lines 382.. = after (line 383 onward)
$before = $arr[0..282]
$after  = $arr[382..($arr.Length - 1)]

$result = $before + $newBlock + $after
[System.IO.File]::WriteAllLines($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Done. Total lines: $($result.Count)"
